[package]
authors = ["Ian O'Connell <ianoc@ianoc.net>"]
edition = "2021"
license = "Apache-2.0"
name = "bazelfe-bazel-wrapper"
version = "0.1.0"

[[bin]]
name = "generate-bazel-command-line"
path = "src/bazel_command_line_parser/generate_bazel_command_line_app.rs"
required-features = ["dev-binaries"]

[dependencies]
async-channel = "1.8.0"
async-stream = "0.3.5"
async-trait = "0.1.68"
byteorder = "1.4.3"
bytes = "1.4.0"
clap = { version = "4.2.7", features = ["derive", "env"] }
ctrlc = "3.2.5"
exec = "0.3.1"
lazy_static = "1.4.0"
log = "0.4.17"
nom = "7.1.3"
pretty_env_logger = "0.4.0"
prost = "0.11.9"
prost-types = "0.11.9"
rand = "0.8.5"
regex = "1.8.1"
serde = { version = "1.0.162", features = ["derive"] }
dynfmt = { version = "0.1.5", features = ["curly"] }
toml = "0.7.3"
walkdir = "2.3.3"
shellwords = "1.1.0"
zip = "0.6.5"
thiserror = "1.0.40"
fork = { version = "0.1.21", optional = true }
serde_json = "1.0.96"
stdio-override = { version = "0.1.3", optional = true }
libc = "0.2.144"
crossbeam-channel = { version = "0.5.8", optional = true }
notify = { version = "5.1.0", optional = true }
tokio-serde = { version = "0.8.0", features = ["bincode"], optional = true }
tokio-util = { version = "0.7.8", features = ["compat"] }
sha2 = "0.10.6"
nix = "0.26.2"
flume = { version = "0.10.14", optional = true }
trim-margin = { version = "0.1.0", optional = true }
dashmap = { version = "5.4.0", optional = true }
tui = { version = "0.19.0", default_features = false, features = ["crossterm"], optional = true }
crossterm = "0.26.1"
muncher = { version = "0.7.0", optional = true }
humantime = "2.1.0"
tempfile = { version = "3.5.0", optional = true }
anyhow = "1.0.71"
ignore = "0.4.20"
tower = "0.4.13"
tokio-signal = "0.2.9"
mio = "0.8.6"
ptyprocess = "0.4.1"
xml-rs = "0.8.9"

[build-dependencies]
anyhow = "1.0.71"

[dependencies.bazelfe-protos]
path = "../bazelfe-protos"

[dependencies.futures]
default-features = false
features = ["alloc", "bilock", "unstable"]
version = "0.3.28"

[dependencies.tokio]
features = ["full"]
version = "1.28.1"

[dependencies.tokio-stream]
features = ["net"]
version = "0.1.14"

[dependencies.tonic]
features = ["tls"]
version = "0.9.2"

[dev-dependencies]
once_cell = "1.17.1"
pinky-swear = "6.1.0"
tower = "0.4.13"
tempfile = "3.5.0"

[features]
default = []
dev-binaries = []
autotest-action = ["tui", "muncher", "tempfile", "bazelfe-daemon"]
bazelfe-daemon = ["notify", "tokio-serde", "flume", "trim-margin", "dashmap", "fork", "stdio-override"]

[lib]
name = "bazelfe_bazel_wrapper"
path = "src/lib.rs"
