[package]
authors = ["Ian O'Connell <ianoc@ianoc.net>"]
edition = "2021"
license = "Apache-2.0"
name = "bzl-remote-core"
version = "0.1.0"
build = "build.rs"

[[bin]]
name = "cache-server"
path = "src/binaries/cache_server/app.rs"


[[bin]]
name = "dump-cache-data"
path = "src/binaries/dump_cache_data/app.rs"


[dependencies]
async-channel = "1.8.0"
async-stream = "0.3.3"
async-trait = "0.1.66"
byteorder = "1.4.3"
bytes = "1.4.0"
clap = { version = "4.1.8", features = ["derive", "env"] }
ctrlc = "3.2.5"
base64 = "0.21.0"
exec = "0.3.1"
lazy_static = "1.4.0"
tracing = "0.1.37"
tracing-attributes = "0.1"
tracing-futures = "0.2"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["tracing-log", "env-filter"] }
prost = "0.11.6"
prost-types = "0.11.8"
rand = "0.8.5"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
dynfmt = { version = "0.1.5", features = ["curly"] }
serde_derive = "1.0.152"
toml = "0.7.2"
thiserror = "1.0.39"
serde_json = "1.0.94"
libc = "0.2.139"
crossbeam-channel = { version = "0.5.7" }
notify = { version = "5.1.0" }
tokio-serde = { version = "0.8.0", features = ["bincode"] }
tokio-util = { version = "0.7.7", features = ["compat"] }
sha2 = "0.10.6"
nix = "0.26.2"
flume = { version = "0.10.14" }
trim-margin = { version = "0.1.0" }
dashmap = { version = "5.4.0" }
muncher = { version = "0.7.0" }
humantime = "2.1.0"
tempfile = { version = "3.4.0" }
anyhow = "1.0.69"
ignore = "0.4.20"
tower = { version = "0.4" }
log = "0.4.17"
hyper = "0.14.24"
hyper-tls = "0.5.0"
sled = "0.34.7"
memmap2 = "0.5.10"
aws-sdk-s3 = "0.24.0"
aws-config = "0.54.1"
aws-smithy-http = "0.54.4"
redis = { version = "0.22.3", features = ["tokio-comp", "connection-manager"] }
urlencoding = "2.1.2"
http = "0.2.9"
http-body = "0.4.5"
sysinfo = "0.28.2"


[build-dependencies]
vergen = "7.5.1"
anyhow = "1.0.69"

[dependencies.bazelfe-protos]
path = "../bazelfe-protos"

[dependencies.futures]
default-features = false
features = ["alloc"]
version = "0.3.26"

[dependencies.tokio]
features = ["full"]
version = "1.26.0"

[dependencies.tokio-stream]
features = ["net"]
version = "0.1.12"

[dependencies.tonic]
features = ["tls"]
version = "0.8.3"

[dev-dependencies]
once_cell = "1.17.1"
pinky-swear = "6.1.0"
tower = "0.4.13"
tempfile = "3.4.0"

[features]
default = []
dev-binaries = []

[lib]
name = "bzl_remote_core"
path = "src/lib.rs"
