[package]
authors = ["Ian O'Connell <ianoc@ianoc.net>"]
edition = "2021"
license = "Apache-2.0"
name = "bzl-remote-core"
version = "0.1.0"
build = "build.rs"

[[bin]]
name = "cache-server"
path = "src/binaries/cache_server/app.rs"


[[bin]]
name = "dump-cache-data"
path = "src/binaries/dump_cache_data/app.rs"


[dependencies]
async-stream = "0.3.5"
async-trait = "0.1.73"
byteorder = "1.4.3"
bytes = "1.4.0"
clap = { version = "4.4.0", features = ["derive", "env"] }
base64 = "0.21.2"
lazy_static = "1.4.0"
openssl = { version = "0.10.56", features = ["vendored"] }
tracing = "0.1.38"
tracing-attributes = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["tracing-log", "env-filter"] }
prost = "0.11.9"
prost-types = "0.11.9"
rand = "0.8.5"
regex = "1.9.3"
serde = { version = "1.0.188", features = ["derive"] }
serde_derive = "1.0.152"
toml = "0.7.6"
thiserror = "1.0.47"
libc = "0.2.147"
crossbeam-channel = { version = "0.5.8" }
tokio-util = { version = "0.7.8", features = ["compat"] }
sha2 = "0.10.7"
flume = { version = "0.11.0" }
dashmap = { version = "5.5.1" }
time = "0.3.28"
tempfile = { version = "3.8.0" }
anyhow = "1.0.75"
tower = { version = "0.4" }
log = "0.4.20"
hyper = "0.14.27"
hyper-tls = "0.5.0"
sled = "0.34.7"
memmap2 = "0.7.1"
aws-sdk-s3 = "0.30.0"
aws-config = "0.56.1"
aws-smithy-http = "0.56.1"
redis = { version = "0.23.2", features = ["tokio-comp", "connection-manager"] }
urlencoding = "2.1.3"
http = "0.2.9"
http-body = "0.4.5"
sysinfo = "0.29.9"


[build-dependencies]
vergen = { version = "8.2.4", features = [ "build", "git", "gitcl" ]}
anyhow = "1.0.75"

[dependencies.bazelfe-protos]
path = "../bazelfe-protos"

[dependencies.futures]
default-features = false
features = ["alloc"]
version = "0.3.28"

[dependencies.tokio]
features = ["full"]
version = "1.32.0"

[dependencies.tokio-stream]
features = ["net"]
version = "0.1.14"

[dependencies.tonic]
features = ["tls"]
version = "0.9.2"

[dev-dependencies]
once_cell = "1.18.0"
pinky-swear = "6.1.0"
tower = "0.4.13"
tempfile = "3.8.0"

[features]
default = []
dev-binaries = []

[lib]
name = "bzl_remote_core"
path = "src/lib.rs"
