[package]
authors = ["Ian O'Connell <ianoc@ianoc.net>"]
edition = "2018"
license = "Apache-2.0"
name = "bazelfe-core"
version = "0.1.0"
build = "build.rs"

[[bin]]
name = "scala-parser"
path = "src/source_dependencies/scala/scala_parser_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "java-parser"
path = "src/source_dependencies/java/java_parser_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "index-table"
path = "src/index_table/load_index_table_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "build-events"
path = "src/build_events/build_events_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "buildozer-driver"
path = "src/buildozer_driver/buildozer_driver_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "generate-bazel-command-line"
path = "src/bazel_command_line_parser/generate_bazel_command_line_app.rs"
required-features = ["dev-binaries"]


[[bin]]
name = "bazel-runner-daemon-demo-app"
path = "src/bazel_runner_daemon/bazel_runner_daemon_demo_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "jvm-indexer"
path = "src/jvm_indexer/jvm_indexer_app.rs"

[[bin]]
name = "bazel-runner"
path = "src/bazel_runner/bazel_runner_app.rs"

[dependencies]
async-channel = "1.6.1"
async-stream = "0.3.2"
async-trait = "0.1.51"
byteorder = "1.4.3"
bytes = "1.1.0"
clap = "3.0.0-beta.4"
ctrlc = "3.2.1"
exec = "0.3.1"
lazy_static = "1.4.0"
log = "0.4"
nom = "7.0.0"
pretty_env_logger = "0.4"
prost = "0.8"
prost-types = "0.8"
rand = "0.8.4"
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
dynfmt = {version ="0.1.5", features = ["curly"]}
serde_derive = "1.0.126"
toml = "0.5.8"
walkdir = "2.3.2"
shellwords = "1.1.0"
zip = "0.5.13"
thiserror = "1.0.30"
fork = {version = "0.1.18", optional=true}
serde_json = "1.0.68"
stdio-override = {version = "0.1.3", optional = true}
libc = "0.2.103"
crossbeam-channel = {version = "0.5.1", optional = true}
notify = {version = "5.0.0-pre.13", optional = true}
tarpc = {version = "0.27.2", features = ["tokio1", "serde1", "serde-transport"], optional=true}
tokio-serde = { version = "0.8", features = ["bincode"] , optional=true}
tokio-util = { version = "0.6.8", features = ["compat"] }
sha2 = "0.9.8"
nix = "0.23.0"
flume = {version = "0.10.9", optional = true}
trim-margin = {version = "0.1.0", optional = true}
dashmap = {version = "4.0.2", optional = true}
tui = {version = "0.16.0", default_features = false, features = ["crossterm"], optional = true}
crossterm = {version = "0.21.0", optional = true}
muncher = {version  = "0.7.0", optional = true}
humantime = "2.1.0"
tempfile = {version = "3.2.0", optional = true}


[build-dependencies]
vergen = "5.1.15"
anyhow = "1.0.44"

[dependencies.bazelfe-protos]
path = "../bazelfe-protos"

[dependencies.futures]
default-features = false
features = ["alloc"]
version = "0.3.17"

[dependencies.tokio]
features = ["full"]
version = "1"

[dependencies.tokio-stream]
features = ["net"]
version = "0.1.7"

[dependencies.tonic]
features = ["tls"]
version = "0.5.2"

[dev-dependencies]
once_cell = "1.8.0"
pinky-swear = "5.1.0"
tower = "0.4"
tempfile = {version = "3.2.0"}

[features]
default = []
dev-binaries = []
autotest-action = ["tui", "crossterm", "muncher", "tempfile", "bazelfe-daemon"]
bazelfe-daemon = ["notify", "tarpc", "tokio-serde", "flume", "trim-margin", "dashmap", "fork", "stdio-override"]

[lib]
name = "bazelfe_core"
path = "src/lib.rs"
