[package]
authors = ["Ian O'Connell <ianoc@ianoc.net>"]
edition = "2021"
license = "Apache-2.0"
name = "bazelfe-core"
version = "0.1.0"
build = "build.rs"

[[bin]]
name = "scala-parser"
path = "src/source_dependencies/scala/scala_parser_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "java-parser"
path = "src/source_dependencies/java/java_parser_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "index-table"
path = "src/index_table/load_index_table_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "build-events"
path = "src/build_events/build_events_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "buildozer-driver"
path = "src/buildozer_driver/buildozer_driver_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "generate-bazel-command-line"
path = "src/bazel_command_line_parser/generate_bazel_command_line_app.rs"
required-features = ["dev-binaries"]


[[bin]]
name = "bazel-runner-daemon-demo-app"
path = "src/bazel_runner_daemon/bazel_runner_daemon_demo_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "jvm-indexer"
path = "src/jvm_indexer/jvm_indexer_app.rs"

[[bin]]
name = "bazel-runner"
path = "src/bazel_runner/bazel_runner_app.rs"

[dependencies]
async-channel = "1.7.1"
async-stream = "0.3.3"
async-trait = "0.1.57"
byteorder = "1.4.3"
bytes = "1.2.1"
clap = { version = "3.2.17", features = ["derive", "env"] }
ctrlc = "3.2.3"
exec = "0.3.1"
lazy_static = "1.4.0"
log = "0.4.17"
nom = "7.1.1"
pretty_env_logger = "0.4.0"
prost = "0.11.0"
prost-types = "0.11.1"
rand = "0.8.5"
regex = "1.6.0"
serde = { version = "1.0.144", features = ["derive"] }
dynfmt = { version = "0.1.5", features = ["curly"] }
serde_derive = "1.0.141"
toml = "0.5.9"
walkdir = "2.3.2"
shellwords = "1.1.0"
zip = "0.6.2"
thiserror = "1.0.33"
fork = { version = "0.1.19", optional = true }
serde_json = "1.0.85"
stdio-override = { version = "0.1.3", optional = true }
libc = "0.2.132"
crossbeam-channel = { version = "0.5.6", optional = true }
notify = { version = "5.0.0-pre.15", optional = true }
tokio-serde = { version = "0.8.0", features = ["bincode"], optional = true }
tokio-util = { version = "0.7.3", features = ["compat"] }
sha2 = "0.10.2"
nix = "0.25.0"
flume = { version = "0.10.14", optional = true }
trim-margin = { version = "0.1.0", optional = true }
dashmap = { version = "5.3.4", optional = true }
tui = { version = "0.19.0", default_features = false, features = ["crossterm"], optional = true }
crossterm = "0.25.0"
muncher = { version = "0.7.0", optional = true }
humantime = "2.1.0"
tempfile = { version = "3.3.0", optional = true }
anyhow = "1.0.62"
ignore = "0.4.18"
tower = "0.4.13"
tokio-signal = "0.2.9"
mio = "0.8.4"
ptyprocess = "0.3.0"


[build-dependencies]
vergen = "7.4.0"
anyhow = "1.0.62"

[dependencies.bazelfe-protos]
path = "../bazelfe-protos"

[dependencies.futures]
default-features = false
features = ["alloc", "bilock", "unstable"]
version = "0.3.23"

[dependencies.tokio]
features = ["full"]
version = "1.20.1"

[dependencies.tokio-stream]
features = ["net"]
version = "0.1.9"

[dependencies.tonic]
features = ["tls"]
version = "0.8.0"

[dev-dependencies]
once_cell = "1.13.1"
pinky-swear = "6.1.0"
tower = "0.4.13"
tempfile = "3.3.0"

[features]
default = []
dev-binaries = []
autotest-action = ["tui", "muncher", "tempfile", "bazelfe-daemon"]
bazelfe-daemon = ["notify", "tokio-serde", "flume", "trim-margin", "dashmap", "fork", "stdio-override"]

[lib]
name = "bazelfe_core"
path = "src/lib.rs"
