[package]
name = "bazelfe-core"
version = "0.1.0"
authors = ["Ian O'Connell <ianoc@ianoc.net>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
rand = "0.8.3"
nom = "6.1.2"
clap = "3.0.0-beta.2"
regex = "1.4.5"
lazy_static = "1.4.0"
futures = { version = "0.3.13", default-features = false, features = ["alloc"] }
tonic = { version = "0.4.1", features = ["tls"] }
prost = "0.7"
tokio = { version = "1", features = ["full"] }
tokio-stream =  { version = "0.1.5", features = ["net"] }
# Required for wellknown types
prost-types = "0.7"
pretty_env_logger = "0.4"
log = "0.4"
async-stream = "0.3.0"
bytes = "1.0.1"
ctrlc = "3.1.8"
async-trait = "0.1.48"
exec = "0.3.1"
zip = "0.5.11"
bazelfe-protos = { path = "../bazelfe-protos" }
walkdir = "2.3.2"
async-channel = "1.6.1"
byteorder = "1.4.3"

[dev-dependencies]
tempfile = "3.2.0"
pinky-swear = "5.1.0"
tower = "0.4"
once_cell = "1.7.2"

[features]
dev-binaries=[]
default = ["dev-binaries"]

[lib]
name = "bazelfe_core"
path = "src/lib.rs"

[[bin]]
name = "scala-parser"
path = "src/source_dependencies/scala/scala_parser_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "java-parser"
path = "src/source_dependencies/java/java_parser_app.rs"
required-features = ["dev-binaries"]


[[bin]]
name = "index-table"
path = "src/index_table/load_index_table_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "build-events"
path = "src/build_events/build_events_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "bazel-runner"
path = "src/bazel_runner/bazel_runner_app.rs"


[[bin]]
name = "buildozer-driver"
path = "src/buildozer_driver/buildozer_driver_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "jvm-indexer"
path = "src/jvm_indexer/jvm_indexer_app.rs"


