[package]
authors = ["Ian O'Connell <ianoc@ianoc.net>"]
edition = "2021"
license = "Apache-2.0"
name = "bazelfe-core"
version = "0.1.0"
build = "build.rs"

[[bin]]
name = "scala-parser"
path = "src/source_dependencies/scala/scala_parser_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "java-parser"
path = "src/source_dependencies/java/java_parser_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "index-table"
path = "src/index_table/load_index_table_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "build-events"
path = "src/build_events/build_events_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "buildozer-driver"
path = "src/buildozer_driver/buildozer_driver_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "generate-bazel-command-line"
path = "src/bazel_command_line_parser/generate_bazel_command_line_app.rs"
required-features = ["dev-binaries"]


[[bin]]
name = "bazel-runner-daemon-demo-app"
path = "src/bazel_runner_daemon/bazel_runner_daemon_demo_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "jvm-indexer"
path = "src/jvm_indexer/jvm_indexer_app.rs"

[[bin]]
name = "bazel-runner"
path = "src/bazel_runner/bazel_runner_app.rs"

[dependencies]
async-channel = "1.6.1"
async-stream = "0.3.3"
async-trait = "0.1.53"
byteorder = "1.4.3"
bytes = "1.1.0"
clap = { version = "3.1.11", features = ["derive", "env"] }
ctrlc = "3.2.2"
exec = "0.3.1"
lazy_static = "1.4.0"
log = "0.4.16"
nom = "7.1.1"
pretty_env_logger = "0.4.0"
prost = "0.10.0"
prost-types = "0.10.1"
rand = "0.8.5"
regex = "1.5.5"
serde = { version = "1.0.136", features = ["derive"] }
dynfmt = { version = "0.1.5", features = ["curly"] }
serde_derive = "1.0.136"
toml = "0.5.9"
walkdir = "2.3.2"
shellwords = "1.1.0"
zip = "0.6.2"
thiserror = "1.0.30"
fork = { version = "0.1.19", optional = true }
serde_json = "1.0.79"
stdio-override = { version = "0.1.3", optional = true }
libc = "0.2.123"
crossbeam-channel = { version = "0.5.4", optional = true }
notify = { version = "5.0.0-pre.14", optional = true }
tokio-serde = { version = "0.8.0", features = ["bincode"], optional = true }
tokio-util = { version = "0.7.1", features = ["compat"] }
sha2 = "0.10.2"
nix = "0.23.1"
flume = { version = "0.10.12", optional = true }
trim-margin = { version = "0.1.0", optional = true }
dashmap = { version = "5.2.0", optional = true }
tui = { version = "0.17.0", default_features = false, features = ["crossterm"], optional = true }
crossterm = { version = "0.23.2", optional = true }
muncher = { version = "0.7.0", optional = true }
humantime = "2.1.0"
tempfile = { version = "3.3.0", optional = true }
anyhow = "1.0.56"
ignore = "0.4.18"
tower = { version = "0.4" }


[build-dependencies]
vergen = "7.0.0"
anyhow = "1.0.56"

[dependencies.bazelfe-protos]
path = "../bazelfe-protos"

[dependencies.futures]
default-features = false
features = ["alloc"]
version = "0.3.21"

[dependencies.tokio]
features = ["full"]
version = "1.17.0"

[dependencies.tokio-stream]
features = ["net"]
version = "0.1.8"

[dependencies.tonic]
features = ["tls"]
version = "0.7.1"

[dev-dependencies]
once_cell = "1.10.0"
pinky-swear = "6.1.0"
tower = "0.4.12"
tempfile = "3.3.0"

[features]
default = []
dev-binaries = []
autotest-action = ["tui", "crossterm", "muncher", "tempfile", "bazelfe-daemon"]
bazelfe-daemon = ["notify", "tokio-serde", "flume", "trim-margin", "dashmap", "fork", "stdio-override"]

[lib]
name = "bazelfe_core"
path = "src/lib.rs"
