[package]
authors = ["Ian O'Connell <ianoc@ianoc.net>"]
edition = "2018"
license = "Apache-2.0"
name = "bazelfe-core"
version = "0.1.0"
build = "build.rs"

[[bin]]
name = "scala-parser"
path = "src/source_dependencies/scala/scala_parser_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "java-parser"
path = "src/source_dependencies/java/java_parser_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "index-table"
path = "src/index_table/load_index_table_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "build-events"
path = "src/build_events/build_events_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "bazel-runner"
path = "src/bazel_runner/bazel_runner_app.rs"

[[bin]]
name = "buildozer-driver"
path = "src/buildozer_driver/buildozer_driver_app.rs"
required-features = ["dev-binaries"]

[[bin]]
name = "jvm-indexer"
path = "src/jvm_indexer/jvm_indexer_app.rs"


[[bin]]
name = "bazel-runner-daemon-demo-app"
path = "src/bazel_runner_daemon/bazel_runner_daemon_demo_app.rs"


[[bin]]
name = "generate-bazel-command-line"
path = "src/bazel_command_line_parser/generate_bazel_command_line_app.rs"



[dependencies]
async-channel = "1.6.1"
async-stream = "0.3.0"
async-trait = "0.1.48"
byteorder = "1.4.3"
bytes = "1.0.1"
clap = "3.0.0-beta.2"
ctrlc = "3.1.9"
exec = "0.3.1"
lazy_static = "1.4.0"
log = "0.4"
nom = "6.1.2"
pretty_env_logger = "0.4"
prost = "0.7"
prost-types = "0.7"
rand = "0.8.3"
regex = "1.4.5"
serde = "1.0.125"
dynfmt = {version ="0.1.5", features = ["curly"]}
serde_derive = "1.0.125"
toml = "0.5.8"
walkdir = "2.3.2"
shellwords = "1.1.0"
zip = "0.5.11"
thiserror = "1.0.24"
fork = "0.1.18"
stdio-override = "0.1.3"
libc = "0.2.94"
crossbeam-channel = "0.4.0"
notify = "5.0.0-pre.7"
tarpc = {version = "0.25.1", features = ["tokio1", "serde1", "serde-transport"]}
tokio-serde = { version = "0.8", features = ["bincode"] }
tokio-util = { version = "0.6.4", features = ["compat"] }
sha2 = "0.9.4"
nix = "0.20.0"
serde_json = "1.0.64"
flume = "0.10.5"
trim-margin = "0.1.0"
dashmap = "4.0.2"

[build-dependencies]
vergen = "5.1.5"
anyhow = "1.0.40"


[dependencies.bazelfe-protos]
path = "../bazelfe-protos"

[dependencies.futures]
default-features = false
features = ["alloc"]
version = "0.3.14"

[dependencies.tokio]
features = ["full"]
version = "1"

[dependencies.tokio-stream]
features = ["net"]
version = "0.1.5"

[dependencies.tonic]
features = ["tls"]
version = "0.4.2"

[dev-dependencies]
once_cell = "1.7.2"
pinky-swear = "5.1.0"
tempfile = "3.2.0"
tower = "0.4"

[features]
default = ["dev-binaries"]
dev-binaries = []

[lib]
name = "bazelfe_core"
path = "src/lib.rs"
